name: Pull request tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Running test with jest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Installing jest
        run: npm install --save-dev jest ts-jest typescript ts-node

      - name: Test suit run
        run: npm run test


